-- Yeni tabloyu oluştur
CREATE TABLE beklentiler_takip (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    kullanici_adi text not null,
    kategori text,           -- Bireysel / Kurumsal
    anket_donemi text not null,  -- Örn: "2025-01" (Verinin Girildiği Ay)
    hedef_donemi text not null,  -- Örn: "2025-12" (Tahmin Edilen Dönem)
    tahmin_tarihi date,          -- Tam tarih (2025-01-15)
    kaynak_link text,
    
    -- Veriler
    tahmin_ppk_faiz numeric, min_ppk_faiz numeric, max_ppk_faiz numeric,
    tahmin_yilsonu_faiz numeric, min_yilsonu_faiz numeric, max_yilsonu_faiz numeric,
    
    tahmin_aylik_enf numeric, min_aylik_enf numeric, max_aylik_enf numeric,
    tahmin_yillik_enf numeric, min_yillik_enf numeric, max_yillik_enf numeric,
    tahmin_yilsonu_enf numeric, min_yilsonu_enf numeric, max_yilsonu_enf numeric,
    
    katilimci_sayisi int default 1
);

-- AYNI KİŞİ, AYNI ANKET DÖNEMİNDE, AYNI HEDEF İÇİN SADECE 1 KEZ KAYIT GİREBİLİR (GÜNCELLER)
ALTER TABLE beklentiler_takip 
ADD CONSTRAINT unique_kullanici_anket_hedef UNIQUE (kullanici_adi, anket_donemi, hedef_donemi);
